// Mocks generated by Mockito 5.4.5 from annotations
// in sign_in_sign_up/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sign_in_sign_up/common/models/app_user.dart' as _i4;
import 'package:sign_in_sign_up/common/repositories/auth_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AppStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppStorage extends _i1.Mock implements _i2.AppStorage {
  MockAppStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveUser(_i4.AppUser? user) => (super.noSuchMethod(
        Invocation.method(
          #saveUser,
          [user],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i4.AppUser? checkUser(
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #checkUser,
        [
          username,
          password,
        ],
      )) as _i4.AppUser?);

  @override
  int getCurrentTheme() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentTheme,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  dynamic saveCurrentTheme(int? value) => super.noSuchMethod(Invocation.method(
        #saveCurrentTheme,
        [value],
      ));

  @override
  void saveUserInStorage(_i4.AppUser? user) => super.noSuchMethod(
        Invocation.method(
          #saveUserInStorage,
          [user],
        ),
        returnValueForMissingStub: null,
      );
}
